### PR TITLE
added pan to scroll capability since setting touch-action to none on the element will disable native browser pan to scroll

### PR DESCRIPTION
**Pull request by chadwickchow**

### CODE REVIEW

**Comment by aichi** [comment]
Hi, thanks for pull request. I see you are solving one painful gap in the library but I am worrying of performance impact of your solution. I see that you are using clientHeight and scrollHeight in the loop of element parents and accessing these properties means that browser have to reflow, see: https://sites.google.com/site/getsnippet/javascript/dom/repaints-and-reflows-manipulating-the-dom-responsibly

Can the improvement be simplified without that perf impact?

**Comment by chadwickchow** [comment]
Hi, yes you are right that should be optimized, thanks for the pointing that out.  I am going to cache the clientHeight and scrollHeight on the element (and clear them at the end) so it won't need to query the values inside the while loop.  I'll submit a new commit.

**Comment by aichi** [comment]
Hi, sorry being late to response, I had to find time to look deeply into the PR code and re-think what it is solving. At the end I am nut sure I understand your scenario. Can you please share some HTML+CSS+JS snipped which shows desired behaviour not working in IE/Edge? Thx.

**Comment by aichi** [comment]
I am going to close this PR because 
- it brings complex code
- there is less and less need for this library

If the change is necessary for your project, please fork.

**Pull request closed without merging**
